"use client";

import React, { useState } from "react";
import {
  ArrowLeft,
  ArrowRight,
  Check,
  Copy,
  Download,
  Loader2,
} from "lucide-react";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { cn } from "@/lib/utils";

/**
 * ReviewStep — PipelineStep = 3.
 *
 * The user has just watched Agent 1 stream a bash script
 * (`src_tenant.sh`). Now they review it, name the tenant, and either
 * download the script for offline use or hand it off to Agent 2 for
 * sandbox build.
 *
 * Layout intent:
 *   ┌─ sticky header ────────────────────────┐
 *   │ [AGENT 1 ✓] Script ready.   subtitle   │
 *   ├────────────────────────────────────────┤
 *   │ body (scrollable):                     │
 *   │   • stats strip                        │
 *   │   • script viewer (fixed-h, inner sc.) │
 *   │   • tenant name section                │
 *   ├────────────────────────────────────────┤
 *   │ [Back] [Download] [Start Build →]      │
 *   └────────────────────────────────────────┘
 *
 * Same English-only wording / Tailwind shape as the other steps.
 *
 * Note: the legacy <CodeViewer> with .code-* classes is intentionally
 * not reused here — Copy/Download live in the panel header (closer to
 * the affordance they act on) and the chrome is plain Tailwind.
 */

interface ReviewStepProps {
  script: string;
  tenantName: string;
  onTenantNameChange: (v: string) => void;
  onBack: () => void;
  onDownload: () => void;
  onProceed: () => void;
  copied: boolean;
  onCopy: () => void;
}

export function ReviewStep({
  script,
  tenantName,
  onTenantNameChange,
  onBack,
  onDownload,
  onProceed,
  copied,
  onCopy,
}: ReviewStepProps) {
  const lines = script.split("\n").length;
  const kb = (script.length / 1024).toFixed(1);
  /* `cat > <path>` is the heredoc preamble Agent 1 emits per file —
     counting it gives us "files generated by the script" without
     parsing the script for real. */
  const files = (script.match(/^cat > /gm) ?? []).length;
  const trimmedTenant = tenantName.trim();
  const canProceed = trimmedTenant.length > 0;

  return (
    <div className="flex h-full min-h-0 w-full flex-col overflow-hidden">
      {/* ── Sticky header ─────────────────────────────────────── */}
      <header
        className={cn(
          "sticky top-0 z-10 border-b border-border bg-background/95 backdrop-blur",
          "px-6 py-4 lg:px-10",
        )}
      >
        <div className="mx-auto flex w-full max-w-[1240px] flex-wrap items-baseline gap-x-3 gap-y-1">
          <AgentDoneBadge label="AGENT 1" />
          <h1 className="font-display text-[22px] font-medium leading-[1.15] tracking-[-0.02em] text-foreground lg:text-[24px]">
            Script ready.
          </h1>
          <p className="min-w-0 flex-1 text-sm leading-snug text-muted-foreground">
            Inspect <code className="font-mono text-[12px]">src_tenant.sh</code>,
            name the tenant, then hand it to Agent 2 — or download it and run
            the build yourself.
          </p>
        </div>
      </header>

      {/* ── Scrollable body ───────────────────────────────────── */}
      <div className="min-h-0 flex-1 overflow-y-auto">
        <div className="mx-auto w-full max-w-[1080px] space-y-5 px-6 py-6 lg:px-10 lg:py-8">
          <StatsStrip files={files} lines={lines} kb={kb} />

          <ScriptViewer
            script={script}
            copied={copied}
            onCopy={onCopy}
            onDownload={onDownload}
          />

          <TenantNameSection
            tenantName={tenantName}
            onTenantNameChange={onTenantNameChange}
          />
        </div>
      </div>

      {/* ── Sticky footer ─────────────────────────────────────── */}
      <footer
        className={cn(
          "sticky bottom-0 z-10 border-t border-border bg-background/95 backdrop-blur",
          "px-6 py-3 lg:px-10",
        )}
      >
        <div className="mx-auto flex w-full max-w-[1240px] items-center justify-between gap-4">
          <Button variant="ghost" size="sm" onClick={onBack}>
            <ArrowLeft className="size-4" aria-hidden="true" />
            <span>Back</span>
          </Button>

          <div className="flex items-center gap-3">
            <Button variant="outline" size="sm" onClick={onDownload}>
              <Download className="size-4" aria-hidden="true" />
              <span>Download .sh</span>
            </Button>
            {!canProceed && (
              <span className="hidden text-xs text-muted-foreground sm:inline">
                Name the tenant to start the build
              </span>
            )}
            <Button onClick={onProceed} disabled={!canProceed} size="lg">
              <span>Start Build</span>
              <ArrowRight className="size-4" aria-hidden="true" />
            </Button>
          </div>
        </div>
      </footer>
    </div>
  );
}

/* ════════════════════════════════════════════════════════════════════
   AgentDoneBadge — green-tinted "✓ AGENT 1" chip.

   Mirrors the chip in GeneratingStep but in the success state: the
   user just left that screen, so visual continuity matters.
   ════════════════════════════════════════════════════════════════════ */

function AgentDoneBadge({ label }: { label: string }) {
  return (
    <span
      className={cn(
        "inline-flex shrink-0 items-center gap-1.5 rounded-full border px-2.5 py-1",
        "border-success-border bg-success text-success-foreground",
        "text-[10px] font-medium uppercase tracking-[0.12em]",
      )}
    >
      <Check className="size-3" aria-hidden="true" />
      {label}
    </span>
  );
}

/* ════════════════════════════════════════════════════════════════════
   StatsStrip — 3 numeric stats in a single horizontal row.

   Compact on purpose: this is a quick "what did we get?" glance, not
   a dashboard. Keep it under one line of vertical real estate.
   ════════════════════════════════════════════════════════════════════ */

function StatsStrip({
  files,
  lines,
  kb,
}: {
  files: number;
  lines: number;
  kb: string;
}) {
  return (
    <div className="grid grid-cols-3 gap-3 sm:gap-4">
      <Stat label="Files" value={files.toLocaleString()} />
      <Stat label="Lines" value={lines.toLocaleString()} />
      <Stat label="Size" value={`${kb} KB`} />
    </div>
  );
}

function Stat({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-lg border border-border bg-card px-4 py-3">
      <div className="font-display text-[20px] font-medium leading-tight tracking-[-0.015em] text-foreground">
        {value}
      </div>
      <div className="mt-0.5 text-[11px] uppercase tracking-[0.1em] text-muted-foreground">
        {label}
      </div>
    </div>
  );
}

/* ════════════════════════════════════════════════════════════════════
   ScriptViewer — fixed-height code panel with header actions.
   ════════════════════════════════════════════════════════════════════ */

function ScriptViewer({
  script,
  copied,
  onCopy,
  onDownload,
}: {
  script: string;
  copied: boolean;
  onCopy: () => void;
  onDownload: () => void;
}) {
  const isEmpty = script.length === 0;

  return (
    <section className="rounded-lg border border-border bg-card">
      {/* Panel header */}
      <header className="flex items-center justify-between border-b border-border/70 px-3.5 py-2">
        <div className="flex items-baseline gap-2">
          <span className="text-[11px] font-medium uppercase tracking-[0.12em] text-muted-foreground">
            src_tenant.sh
          </span>
          {!isEmpty && (
            <span className="font-mono text-[11px] text-muted-foreground/70">
              bash
            </span>
          )}
        </div>
        <div className="flex items-center gap-1">
          <PanelButton
            onClick={onCopy}
            ariaLabel={copied ? "Copied" : "Copy script"}
            tone={copied ? "success" : "default"}
          >
            {copied ? (
              <Check className="size-3.5" aria-hidden="true" />
            ) : (
              <Copy className="size-3.5" aria-hidden="true" />
            )}
            <span>{copied ? "Copied" : "Copy"}</span>
          </PanelButton>
          <PanelButton onClick={onDownload} ariaLabel="Download script">
            <Download className="size-3.5" aria-hidden="true" />
            <span>.sh</span>
          </PanelButton>
        </div>
      </header>

      {/* Code body — fixed height, scrolls inside */}
      <div
        className={cn(
          "h-[420px] overflow-y-auto px-4 py-3",
          "font-mono text-[12.5px] leading-[1.55] text-foreground",
        )}
      >
        {isEmpty ? (
          <span className="inline-flex items-center gap-2 text-muted-foreground/70">
            <Loader2 className="size-3.5 animate-spin" aria-hidden="true" />
            Awaiting script…
          </span>
        ) : (
          <pre className="whitespace-pre">{script}</pre>
        )}
      </div>
    </section>
  );
}

function PanelButton({
  children,
  onClick,
  ariaLabel,
  tone = "default",
}: {
  children: React.ReactNode;
  onClick: () => void;
  ariaLabel: string;
  tone?: "default" | "success";
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      aria-label={ariaLabel}
      className={cn(
        "inline-flex items-center gap-1.5 rounded-md px-2 py-1",
        "text-[11px] font-medium",
        "transition-colors duration-150",
        "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-1 focus-visible:ring-offset-background",
        tone === "success"
          ? "text-success-indicator hover:bg-success/60"
          : "text-muted-foreground hover:bg-muted hover:text-foreground",
      )}
    >
      {children}
    </button>
  );
}

/* ════════════════════════════════════════════════════════════════════
   TenantNameSection — the one piece of input on this screen.

   Sanitizes the preview command but does NOT mutate state — the agent
   downstream is responsible for slug normalisation. We just preview
   what the CLI command will look like so the user isn't surprised.
   ════════════════════════════════════════════════════════════════════ */

function TenantNameSection({
  tenantName,
  onTenantNameChange,
}: {
  tenantName: string;
  onTenantNameChange: (v: string) => void;
}) {
  /* Local "did the user touch the field" tracker. The pipeline state
     starts empty for everyone, so showing the validation hint on
     mount would be obnoxious. */
  const [touched, setTouched] = useState(false);
  const trimmed = tenantName.trim();
  const previewSlug = previewTenantSlug(trimmed) || "tenant";
  const showError = touched && trimmed.length === 0;

  return (
    <section className="rounded-lg border border-border bg-card p-5">
      <div className="space-y-1.5">
        <Label htmlFor="tenant-name" className="text-sm font-medium">
          Tenant name
        </Label>
        <p className="text-[13px] leading-snug text-muted-foreground">
          Used as the workspace folder name. Lowercase, no spaces — extra
          characters get stripped automatically.
        </p>
      </div>
      <Input
        id="tenant-name"
        type="text"
        placeholder="e.g. santamamma"
        value={tenantName}
        onChange={(e) => onTenantNameChange(e.target.value)}
        onBlur={() => setTouched(true)}
        autoComplete="off"
        spellCheck={false}
        className={cn(
          "mt-3 h-10",
          showError && "border-destructive-ring focus-visible:ring-destructive-ring",
        )}
      />
      <div
        className={cn(
          "mt-2 font-mono text-[12px] text-muted-foreground",
          "overflow-x-auto whitespace-nowrap",
        )}
      >
        <span className="text-muted-foreground/70">$ </span>
        <span>npx @olonjs/cli new tenant {previewSlug}</span>
      </div>
      {showError && (
        <p className="mt-2 text-[12px] text-destructive-foreground">
          Tenant name is required to start the build.
        </p>
      )}
    </section>
  );
}

/**
 * Mirrors the slug rules used by @olonjs/cli for the preview line so
 * the user sees roughly what the CLI will receive. Cosmetic only —
 * the real normalisation happens downstream.
 */
function previewTenantSlug(raw: string): string {
  return raw
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .replace(/-{2,}/g, "-");
}
